# Generated by Django 3.2 on 2021-04-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='producer',
            field=models.CharField(db_index=True, default=3, max_length=30),
            preserve_default=False,
        ),
    ]
